### ISSUE TITLE
Support for .net core 

### ISSUE THREAD

**Issue by nyghtrocker** [markjulmar/smpp.net#1]
Hi, I have a .net core 2.0 project and I'm planning to implement SMS functionality. is this package will wokr in .net core 2.0?

**Comment by markjulmar** [comment]
In theory it _should_. You'll have to take the source and recompile it, but I think all the `Socket` classes are present in .NET Standard so it should work.

**Comment by smadurange** [comment]
Open the Smpp.NET project file and replace the content in the file with:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Version>0.1.0</Version>
    <Authors>JulMar Technology, Inc.</Authors>
    <Company>JulMar Technology, Inc.</Company>
    <Copyright>Copyright ©  2008 JulMar Technolgy, Inc.</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Elements\" />
    <Folder Include="Properties\" />
  </ItemGroup>

</Project>
```
And delete the AssemblyInfo.cs. Seems to work with .Net Core.
