### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by FWaqidi** [markjulmar/smpp.net#5]

**Comment by MahmoodRasooli** [comment]
I'm facing the same problem. Did you solve the problem by any chance?
@FWaqidi

**Comment by FWaqidi** [comment]
hi
Just Used iso-8859-1 Character set
<https://www.marxists.org/admin/charsets/index.htm>
Regards

**Comment by MahmoodRasooli** [comment]
Thanks, brother. Really Appreciate the help.
Regards
